services:

  drawio:
    image: jgraph/drawio:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - '${HOST_IP}:${HOST_PORT_HTTP}:8080'
      - '${HOST_IP}:${HOST_PORT_HTTPS}:8443'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
