services:

  ddns-go:
    image: jeessy/ddns-go:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    network_mode: host
    volumes:
      - 'data:/root'
      - '/etc/localtime:/etc/localtime:ro'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  data:
