version: '3.8'

services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:3.0.0
    container_name: xxl-job-admin
    ports:
      - "8181:8181"
    environment:
      PARAMS: '--server.port=8181
              --server.servlet.context-path=/xxl-job-admin
              --spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
              --spring.datasource.username=${MYSQL_USERNAME}
              --spring.datasource.password=${MYSQL_PASSWORD}
              --xxl.job.accessToken=${ACCESS_TOKEN}'
    volumes:
      - applogs:/data/applogs
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4g

volumes:
  applogs:
