services:

  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Shanghai'
      - 'PASSWORD=${PASSWORD}'
      - 'SUDO_PASSWORD=${SUDO_PASSWORD}'
      - 'DEFAULT_WORKSPACE=/config/workspace'
    ports:
      - '18443:8443'
    volumes:
      - 'data:/config'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'

volumes:
  data:
