services:

  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    ports:
      - '38080:8080'
    volumes:
      - 'config:/home/coder/.config'
      - 'project:/home/coder/project'
    user: '${UID}:${GID}'
    environment:
      - 'DOCKER_USER=${USER}'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'

volumes:
  data:
