services:

  code-server:
    image: linuxserver/code-server:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'PASSWORD=${PASSWORD}'
      - 'SUDO_PASSWORD=${SUDO_PASSWORD}'
      - 'DEFAULT_WORKSPACE=${DEFAULT_WORKSPACE}'
    ports:
      - '${HOST_IP}:${HOST_PORT}:8443'
    volumes:
      - 'data:/config'
      - '/etc/localtime:/etc/localtime:ro'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  data:
