services:

  sonarqube:
    image: sonarqube:${IMAGE_TAG}
    hostname: ${CONTAINER_NAME}
    container_name: ${CONTAINER_NAME}
    environment:
      - 'SONAR_JDBC_URL=${SONAR_JDBC_URL}'
      - 'SONAR_JDBC_USERNAME=${SONAR_JDBC_USERNAME}'
      - 'SONAR_JDBC_PASSWORD=${SONAR_JDBC_PASSWORD}'
    volumes:
      - 'data:/opt/sonarqube/data'
      - 'extensions:/opt/sonarqube/extensions'
      - 'logs:/opt/sonarqube/logs'
      - 'temp:/opt/sonarqube/temp'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '${HOST_IP}:${HOST_PORT}:9000'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  data:
  temp:
  extensions:
  logs:
