services:

  es-exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    command:
      - '--es.uri=http://${ES_ADDRESS}'
    ports:
      - '${HOST_IP}:${HOST_PORT}:9114'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
