services:

  elasticsearch-exporter:
    image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.5.0
    container_name: elasticsearch-exporter
    command:
      - '--es.uri=http://${ES_ADDRESS}'
    ports:
      - '9114:9114'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
