services:

  bitwarden:
    image: vaultwarden/server:1.34.1-alpine
    container_name: bitwarden
    ports:
      - '10080:80'
    volumes:
      - 'data:/data'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

volumes:
  data:
