services:

  redis-exporter:
    image: oliver006/redis_exporter:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    command:
      - '-redis.addr=${REDIS_ADDR}'
      - '-redis.password=${REDIS_PASSWORD}'
    ports:
      - '${HOST_PORT}:9121'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
