services:

  lobechat:
    image: lobehub/lobe-chat
    container_name: lobechat
    ports:
      - '3210:3210'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
