services:

  redis01:
    image: bitnami/redis-cluster:7.4.2
    container_name: redis01
    ports:
      - '6381:6381' # redis连接用端口
      - '16381:16381' # redis之间消息连接的端口 默认是redis连接端口+10000
    volumes:
      - 'data1:/bitnami/redis/data'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${HOST_IP}'
      - 'REDIS_PORT_NUMBER=6381' # 替换原始6379端口
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no' # 标明不使用动态IP
      - 'REDIS_PASSWORD=YOUR_PASSWORD' # 认证密码
      - 'REDIS_NODES=${HOST_IP}:6381 ${HOST_IP}:6382 ${HOST_IP}:6383 ${HOST_IP}:6384 ${HOST_IP}:6385 ${HOST_IP}:6386' # 集群节点IP端口
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'

  redis02:
    image: bitnami/redis-cluster:7.4.2
    container_name: redis02
    ports:
      - '6382:6382'
      - '16382:16382'
    volumes:
      - 'data2:/bitnami/redis/data'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${HOST_IP}'
      - 'REDIS_PORT_NUMBER=6382'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_PASSWORD=YOUR_PASSWORD'
      - 'REDIS_NODES=${HOST_IP}:6381 ${HOST_IP}:6382 ${HOST_IP}:6383 ${HOST_IP}:6384 ${HOST_IP}:6385 ${HOST_IP}:6386'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'

  redis03:
    image: bitnami/redis-cluster:7.4.2
    container_name: redis03
    ports:
      - '6383:6383'
      - '16383:16383'
    volumes:
      - 'data3:/bitnami/redis/data'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - 'REDIS_PASSWORD=YOUR_PASSWORD'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${HOST_IP}'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_PORT_NUMBER=6383'
      - 'REDIS_NODES=${HOST_IP}:6381 ${HOST_IP}:6382 ${HOST_IP}:6383 ${HOST_IP}:6384 ${HOST_IP}:6385 ${HOST_IP}:6386'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'

  redis04:
    image: bitnami/redis-cluster:7.4.2
    container_name: redis04
    ports:
      - '6384:6384'
      - '16384:16384'
    volumes:
      - 'data4:/bitnami/redis/data'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - 'REDIS_PASSWORD=YOUR_PASSWORD'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${HOST_IP}'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_PORT_NUMBER=6384'
      - 'REDIS_NODES=${HOST_IP}:6381 ${HOST_IP}:6382 ${HOST_IP}:6383 ${HOST_IP}:6384 ${HOST_IP}:6385 ${HOST_IP}:6386'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'

  redis05:
    image: bitnami/redis-cluster:7.4.2
    container_name: redis05
    ports:
      - '6385:6385'
      - '16385:16385'
    volumes:
      - 'data5:/bitnami/redis/data'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - 'REDIS_PASSWORD=YOUR_PASSWORD'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${HOST_IP}'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_PORT_NUMBER=6385'
      - 'REDIS_NODES=${HOST_IP}:6381 ${HOST_IP}:6382 ${HOST_IP}:6383 ${HOST_IP}:6384 ${HOST_IP}:6385 ${HOST_IP}:6386'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'

  redis06:
    image: bitnami/redis-cluster:7.4.2
    container_name: redis06
    ports:
      - '6386:6386'
      - '16386:16386'
    volumes:
      - 'data6:/bitnami/redis/data'
      - '/etc/localtime:/etc/localtime:ro'
    depends_on:
      - redis01
      - redis02
      - redis03
      - redis04
      - redis05
    environment:
      - 'REDIS_PASSWORD=YOUR_PASSWORD'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=${HOST_IP}'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_PORT_NUMBER=6386'
      - 'REDISCLI_AUTH=YOUR_PASSWORD'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=${HOST_IP}:6381 ${HOST_IP}:6382 ${HOST_IP}:6383 ${HOST_IP}:6384 ${HOST_IP}:6385 ${HOST_IP}:6386'
      - 'REDIS_CLUSTER_CREATOR=yes'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'

volumes:
  data1:
  data2:
  data3:
  data4:
  data5:
  data6:
