services:

  db:
    image: abcfy2/zhparser:${DB_IMAGE_TAG}
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    logging:
      driver: none
    restart: ${RESTART_POLICY}
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: ${DB_CPU_LIMIT}
          memory: ${DB_MEMORY_LIMIT}

  wiki:
    image: ghcr.io/requarks/wiki:${WIKI_IMAGE_TAG}
    container_name: ${WIKI_CONTAINER_NAME}
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    restart: ${RESTART_POLICY}
    ports:
      - "${HOST_IP}:${WIKI_HOST_PORT}:3000"
    deploy:
      resources:
        limits:
          cpus: ${WIKI_CPU_LIMIT}
          memory: ${WIKI_MEMORY_LIMIT}

volumes:
  db-data: