services:

  nextchat:
    image: yidadaa/chatgpt-next-web
    container_name: nextchat
    ports:
      - '3000:3000'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
