services:

  moments:
    image: kingwrcy/moments:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    ports:
      - '${HOST_IP}:${HOST_PORT}:${MOMENTS_SERVER_PORT}'
    volumes:
      - 'data:/app/data'
    environment:
      - 'PORT=${MOMENTS_SERVER_PORT}'
      - 'JWT_KEY=${MOMENTS_JWT_KEY}'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  data: