services:

  moments:
    image: kingwrcy/moments:latest
    container_name: moments
    environment:
      - 'PORT=30000'
      - 'JWT_KEY=24ef6995-d9c9-47b4-8a55-2c74a94796c6'
    ports:
      - '30000:30000'
    volumes:
      - 'data:/app/data'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

volumes:
  data:
