services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - '13000:3000'
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Shanghai'
      - 'HOMEPAGE_ALLOWED_HOSTS=${HOST_IP}:13000'
    volumes:
      - 'config:/app/config'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

volumes:
  config:
