services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - '${HOST_IP}:${HOST_PORT}:8080'
    environment:
      - 'OLLAMA_BASE_URL=${OLLAMA_ADDRESS}'
    volumes:
      - 'open-webui-data:/app/backend/data'
      - '/etc/localtime:/etc/localtime:ro'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  open-webui-data:
