services:
  
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - '46000:8080'
    environment:
      - 'OLLAMA_BASE_URL=${OLLAMA_ADDRESS}'
    volumes:
      - 'open-webui:/app/backend/data'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'

volumes:
  open-webui:
