services:

  xxl-job-admin:
    image: xuxueli/xxl-job-admin:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - '${HOST_PORT}:8181'
    volumes:
      - 'applogs:/data/applogs'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - 'PARAMS= --server.port=8181
              --server.servlet.context-path=${CONTEXT_PATH}
              --spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
              --spring.datasource.username=${MYSQL_USERNAME}
              --spring.datasource.password=${MYSQL_PASSWORD}
              --xxl.job.accessToken=${ACCESS_TOKEN}'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  applogs:
