services:

  kafka-exporter:
    image: danielqsj/kafka-exporter:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - '${HOST_PORT}:9308'
    command:
      - "--kafka.server=${KAFKA_SERVER_01}"
      - "--kafka.server=${KAFKA_SERVER_02}"
      - "--kafka.server=${KAFKA_SERVER_03}"
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}
