services:

  certimate:
    image: certimate/certimate:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    ports:
      - '${HOST_IP}:${HOST_PORT}:8090'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - 'data:/app/pb_data'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  data:
