services:

  certimate:
    image: certimate/certimate:latest
    container_name: certimate
    ports:
      - '28090:8090'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
      - 'data:/app/pb_data'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

volumes:
  data:
