services:

  web:
    image: whyour/qinglong:latest
    container_name: qinglong
    volumes:
      - './data:/ql/data'
    ports:
      - '5700:5700'
    environment:
      - 'QlBaseUrl= /'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'
