services:

  qinglong:
    image: whyour/qinglong:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    volumes:
      - 'data:/ql/data'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '${HOST_IP}:${HOST_PORT}:5700'
    environment:
      - 'QlBaseUrl=${QL_BASE_URL}'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  data:
