services:

  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - 'PUID=1000'
      - 'PGID=1000'
      - 'TZ=Asia/Shanghai'
      - 'PASSWORD=YOUR_PASSWORD'
    volumes:
      - '/path/to/librespeed/config:/config'
    ports:
      - '40080:80'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
