services:

  librespeed:
    image: lscr.io/linuxserver/librespeed:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'TZ=${TZ}'
      - 'PASSWORD=${PASSWORD}'
    volumes:
      - 'config:/config'
    ports:
      - '${HOST_IP}:${HOST_PORT}:80'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  config:
