services:
  
  nexus3:
    image: sonatype/nexus3:3.81.1
    container_name: nexus3
    ports:
      - '18081:8081'
    volumes:
      - 'data:/nexus-data'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '4G'

volumes:
  data:
