version: '2.1'

services:
  nexus3:
    image: sonatype/nexus3:3.81.1
    container_name: nexus3
    restart: unless-stopped
    ports:
      - "18081:8081"
    volumes:
      - data:/nexus-data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
    mem_limit: 4g

volumes:
  data:
