services:

  jenkins:
    image: jenkins/jenkins:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - '${HOST_IP}:${HOST_HTTP_PORT}:8080'
      - '${HOST_IP}:${HOST_JNLP_PORT}:50000'
    volumes:
      - 'data:/var/jenkins_home'
      - '/etc/localtime:/etc/localtime:ro'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  data:
