services:

  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    ports:
      - '28080:8080'
      - '50000:50000'
    volumes:
      - 'data:/var/jenkins_home'
      - '/etc/localtime:/etc/localtime:ro'
    mem_limit: 4g
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '4G'

volumes:
  data:
