version: '2.1'

services:
  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    restart: unless-stopped
    ports:
      - '28080:8080'
      - '50000:50000'
    volumes:
      - data:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
    mem_limit: 4g

volumes:
  data:
