services:

  zookeeper:
    image: bitnami/zookeeper:3.6.1
    container_name: zookeeper
    environment:
      - 'ALLOW_ANONYMOUS_LOGIN=yes'
    ports:
      - '2182:2181'
    volumes:
      - 'zoo_data:/bitnami/zookeeper/data'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

  kafka:
    image: bitnami/kafka:2.5.0
    container_name: kafka
    ports:
      - '9093:9092'
    volumes:
      - 'kafka_data:/bitnami/kafka/data'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - 'ALLOW_PLAINTEXT_LISTENER=yes'
      - 'KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181'
      - 'KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092'
      - 'KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${HOST_IP}:9093'
    depends_on:
      - zookeeper
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

volumes:
  zoo_data:
  kafka_data:
