services:

  alist:
    image: xhofe/alist:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - '${HOST_IP}:${PANEL_APP_PORT_HTTP}:5244'
      - '${HOST_IP}:${PANEL_APP_PORT_S3}:5426'
    volumes:
      - 'alist_data:/opt/alist/data'
      - 'mnt_data:/mnt/data'
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'UMASK=${UMASK}'
      - 'TZ=${TZ}'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  alist_data:
  mnt_data:
