services:
  
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - '9001:9000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'data:/data'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'

volumes:
  data:
