services:

  portainer:
    image: portainer/portainer-ce:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - '${HOST_IP}:${HOST_PORT}:9000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'data:/data'
      - '/etc/localtime:/etc/localtime:ro'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  data:
