services:

  redis:
    image: bitnami/redis:7.4.2
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - 'data:/bitnami/redis/data'
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - 'REDIS_PASSWORD=YOUR_PASSWORD'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'

volumes:
  data:
