version: '2.1'

services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    volumes:
      - data:/var/opt/memos
    ports:
      - '25230:5230'
    mem_limit: 4g

volumes:
  data: