services:

  memos:
    image: neosmemo/memos:stable
    container_name: memos
    volumes:
      - 'data:/var/opt/memos'
    ports:
      - '25230:25230'
    environment:
      - 'MEMOS_PORT=25230'
      - 'TZ=Asia/Shanghai'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

volumes:
  data:
