services:

  memos:
    image: neosmemo/memos:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    volumes:
      - 'data:/var/opt/memos'
    ports:
      - '${HOST_PORT}:${MEMOS_PORT}'
    environment:
      - 'MEMOS_PORT=${MEMOS_PORT}'
      - 'TZ=${TIMEZONE}'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  data:
