services:

  openlist:
    image: openlistteam/openlist:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    volumes:
      - 'data:/opt/openlist/data'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '${HOST_IP}:${HOST_PORT}:5244'
    environment:
      - 'PUID=${PUID}'
      - 'PGID=${PGID}'
      - 'UMASK=${UMASK}'
      - 'TZ=${TZ}'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  data:
