services:

  showdoc:
    image: star7th/showdoc:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    ports:
      - '${HOST_IP}:${HOST_PORT}:80'
    volumes:
      - 'data:/var/www/html/'
      - '/etc/localtime:/etc/localtime:ro'
    restart: ${RESTART_POLICY}
    deploy:
      resources:
        limits:
          cpus: ${CPU_LIMIT}
          memory: ${MEMORY_LIMIT}

volumes:
  data:
