services:
  
  showdoc:
    image: star7th/showdoc
    container_name: showdoc
    ports:
      - '20080:80'
    volumes:
      - 'data:/var/www/html/'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

volumes:
  data:
