services:
  
  redisinsight:
    image: redis/redisinsight:2.60
    container_name: redisinsight
    ports:
      - '5540:5540'
    volumes:
      - 'data:/data'
      - '/etc/localtime:/etc/localtime:ro'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'

volumes:
  data:
