services:

  metersphere:
    image: metersphere/metersphere-ce-allinone:latest
    container_name: ${CONTAINER_NAME}
    ports:
      - ${HOST_IP}:${HOST_PORT}:8081
    volumes:
      - logs:/opt/metersphere/logs
      - data:/opt/metersphere/data
      - conf:/opt/metersphere/conf
    environment:
      JAVA_MAX_HEAP_RATIO: ${JAVA_MAX_HEAP_RATIO}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}

volumes:
  logs:
  data:
  conf:
